name: screenspot_pro CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest pillow
      - name: Run unit tests
        run: PYTHONPATH=. pytest -q
      - name: Mock eval smoke test
        run: |
          PYTHONPATH=. python -m envs.screenspot_pro.eval \
            --annotations data/mock_screenspot_pro/annotations.jsonl \
            --root . --subset 10 --max_resolution 1200 \
            --baseline text --per_example_file /tmp/out_text_scaled_ci.json
